In [1]:
# 데이터 생성 : 소수 계산 위한 타입 지정 0.,1. 
X = [[0.,0.], [1.,1.]]
y = [[0, 1], [1, 1]]

In [2]:
# neural network 함수 load
from sklearn.neural_network import MLPClassifier

In [5]:
# 모델 사용
# solver = "lbfgs" : 알고리즘 지정
# alpha = 1e-5 : 학습에 대한 제약 (작을 수록 제약 없으며, 큰 수치 일 수록 과적합 방지)
# hidden_layer_sizes = (5, 2) : 2개의 은닉층을 생성, hidden layer의 노드(퍼셉트론) 수는 5개, 두 번째의 hidden layer의 노드 수는 2개 생성
# random_state= 1 : 결과와 동일성을 위한 난수 고정
clf = MLPClassifier(solver = "lbfgs", alpha = 1e-5, hidden_layer_sizes = (5, 2),
                    random_state= 1)
clf.fit(X, y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

In [7]:
# 예측
clf.predict([[2.,2.],[-1.,-2]])
# 1,1보다 작을 경우는 [0,1] 분류, [1,1]보다 크거나 작을 경우 [0,1]로 분류

array([[1, 1],
       [0, 1]])

In [9]:
# weights 확인
clf.coefs_
# coefs_ : Neural NEtwork에 속하는 hidden layer에 적용되는 weight

[array([[-0.15011367, -0.62860541, -0.90433213, -3.45938109, -0.63904618],
        [-0.73749132, -1.5947694 , -0.2793927 , -3.28854097,  0.0702225 ]]),
 array([[ 0.30838904, -0.14960207],
        [ 3.14928608, -0.65056811],
        [-0.54615798,  0.54407041],
        [ 4.36386369, -0.33753023],
        [ 0.34792663,  0.68091737]]),
 array([[-3.58233912,  2.68515229],
        [ 0.9049651 , -0.96123048]])]

In [11]:
# layer shape 확인
[coef.shape for coef in clf.coefs_]
# (input 2개 >> 첫 번째 은닉층의 5개의 퍼셉트론(노드)) 
# (첫 번째 은닉층의 5개의 퍼셉트론(노드) >> 두 번째 은닉층의 2개 노드)
# (두 번째 은닉층의 2개 노드 >> output 2개)

[(2, 5), (5, 2), (2, 2)]